services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  fastapi:
    build: .
    ports:
      - "${PORT:-10000}:${PORT:-10000}"
    env_file:
      - .env
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - OLLAMA_URL=http://ollama:11434
    restart: unless-stopped

volumes:
  ollama_data: 